name: Test Fluent Bit Parser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-fluent-bit-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up directories
        run: |
          mkdir -p csv conf output

      - name: Run Fluent Bit
        run: |
          docker run --rm -v $(pwd)/csv:/csv -v $(pwd)/conf:/conf -v $(pwd)/output:/output fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -c /conf/fluent-bit.conf

      - name: Display output
        run: |
          cat output/output.json || echo "No output file generated yet"

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fluent-bit-output
          path: output/
          retention-days: 7